version: '3.8'

services:
  info-auto:
    image: info-auto:v1.2
    container_name: info-auto
    ports:
      - "55823:5000"  # 将宿主机的8080端口映射到容器的8080端口
    volumes:
      - .:/app
    working_dir: /app
    tty: true
    stdin_open: true
    command: python webUI.py
