version: '3.8'

services:
  info-auto:
    image: info-auto:v1.3
    container_name: info-auto
    ports:
      - "55823:5000"
    volumes:
      - .:/app
    working_dir: /app
    tty: true
    stdin_open: true
    environment:
      - PYTHONUNBUFFERED=1  # 禁用Python输出缓冲，确保日志实时输出
    command: >
      bash -c "mkdir -p logs && python webUI.py > >(tee -a log/system.log) 2> >(tee -a log/system-error.log >&2)"
